silant-master/silant_proj/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CarListView.as_view(), name="index"),
    path('user_index', views.AdminIndexListView.as_view(), name="user_index"),
    path('cars/new', views.CarCreateView.as_view(), name="car-create"),
    path('cars/<int:pk>', views.CarDetailView.as_view(), name="car-detail"),
    path('cars/edit/<int:pk>', views.CarUpdateView.as_view(), name="car-update"),
    path('cars/delete/<int:pk>', views.CarDeleteView.as_view(), name="car-delete"),

    path('lookups', views.lookups, name="lookups"),

    path('lookups/vehicle_models', views.VehicleModelListView.as_view(), name="vehicle-model-list"),
    path('lookups/vehicle_models/new', views.VehicleModelCreateView.as_view(), name="vehicle-model-create"),
    path('lookups/vehicle_models/edit/<int:pk>', views.VehicleModelUpdateView.as_view(), name="vehicle-model-update"),

    path('lookups/engine_models', views.EngineModelListView.as_view(), name="engine-model-list"),
    path('lookups/engine_models/new', views.EngineModelCreateView.as_view(), name="engine-model-create"),
    path('lookups/engine_models/edit/<int:pk>', views.EngineModelUpdateView.as_view(), name="engine-model-update"),

    path('lookups/transmission_models', views.TransmissionModelListView.as_view(), name="transmission-model-list"),
    path('lookups/transmission_models/new', views.TransmissionModelCreateView.as_view(), name="transmission-model-create"),
    path('lookups/transmission_models/edit/<int:pk>', views.TransmissionModelUpdateView.as_view(), name="transmission-model-update"),

    path('lookups/drive_axles', views.DriveAxleListView.as_view(), name="drive-axle-list"),
    path('lookups/drive_axles/new', views.DriveAxleCreateView.as_view(), name="drive-axle-create"),
    path('lookups/drive_axles/edit/<int:pk>', views.DriveAxleUpdateView.as_view(), name="drive-axle-update"),

    path('lookups/steering_axles', views.SteeringAxleListView.as_view(), name="steering-axle-list"),
    path('lookups/steering_axles/new', views.SteeringAxleCreateView.as_view(), name="steering-axle-create"),
    path('lookups/steering_axles/edit/<int:pk>', views.SteeringAxleUpdateView.as_view(), name="steering-axle-update"),

    path('lookups/service_companies', views.ServiceCompanyListView.as_view(), name="service-company-list"),
    path('lookups/service_companies/new', views.ServiceCompanyCreateView.as_view(), name="service-company-create"),
    path('lookups/service_companies/edit/<int:pk>', views.ServiceCompanyUpdateView.as_view(), name="service-company-update"),

    path('lookups/maintenance_types', views.MaintenanceTypeListView.as_view(), name="maintenance-type-company-list"),
    path('lookups/maintenance_types/new', views.MaintenanceTypeCreateView.as_view(), name="maintenance-type-create"),
    path('lookups/maintenance_types/edit/<int:pk>', views.MaintenanceTypeUpdateView.as_view(), name="maintenance-type-update"),

    path('lookups/denial_types', views.DenialTypeListView.as_view(), name="denial-type-company-list"),
    path('lookups/denial_types/new', views.DenialTypeCreateView.as_view(), name="denial-type-create"),
    path('lookups/denial_types/edit/<int:pk>', views.DenialTypeUpdateView.as_view(), name="denial-type-update"),

    path('lookups/recovery_methods', views.RecoveryMethodListView.as_view(), name="recovery-method-company-list"),
    path('lookups/recovery_methods/new', views.RecoveryMethodCreateView.as_view(), name="recovery-method-create"),
    path('lookups/recovery_methods/edit/<int:pk>', views.RecoveryMethodUpdateView.as_view(), name="recovery-method-update"),

    path('maintenance', views.MaintenanceListView.as_view(), name="maintenance-list"),
    path('maintenance/new', views.MaintenanceCreateView.as_view(), name="maintenance-create"),
    path('maintenance/<int:pk>', views.MaintenanceDetailView.as_view(), name="maintenance-detail"),
    path('maintenance/edit/<int:pk>', views.MaintenanceUpdateView.as_view(), name="maintenance-update"),
    path('maintenance/delete/<int:pk>', views.MaintenanceDeleteView.as_view(), name="maintenance-delete"),

    path('complaints', views.ComplaintListView.as_view(), name="complaint-list"),
    path('complaints/new', views.ComplaintCreateView.as_view(), name="complaint-create"),
    path('complaints/<int:pk>', views.ComplaintDetailView.as_view(), name="complaint-detail"),
    path('complaints/edit/<int:pk>', views.ComplaintUpdateView.as_view(), name="complaint-edit"),
    path('complaints/delete/<int:pk>', views.ComplaintDeleteView.as_view(), name="complaint-delete"),
]

silant-master/silant_proj/silant_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('authentication.urls')),
    path('', include('main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

silant-master/silant_proj/main/models.py
from django.db import models
from authentication import models as auth_models


"""Модель техники"""
class VehicleModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель техники"
        verbose_name_plural = "Модели техники"


"""Модель двигателя"""
class EngineModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель двигателя"
        verbose_name_plural = "Модели двигателя"


"""Модель трансмиссии"""
class TransmissionModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель трансмиссии"
        verbose_name_plural = "Модели трансмиссии"


"""Модель ведущего моста"""
class DriveAxleModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель ведущего моста"
        verbose_name_plural = "Модели ведущего моста"


"""Модель управляемого моста"""
class SteeringAxleModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель управляемого моста"
        verbose_name_plural = "Модели управляемого моста"


"""Сервисная компания"""
class ServiceCompany(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    user = models.OneToOneField(auth_models.CustomUser, on_delete=models.SET_NULL, verbose_name='Пользователь', null=True)

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Сервисная компания"
        verbose_name_plural = "Сервисные компании"


"""Узел отказа"""
class FailureNode(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Узел отказа"
        verbose_name_plural = "Узлы отказа"


"""Способ восстановления"""
class RecoveryMethod(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Способ восстановления"
        verbose_name_plural = "Способы восстановления"


"""Вид ТО"""
class MaintenanceType(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Вид ТО"
        verbose_name_plural = "Виды ТО"


"""Машина"""
class Car(models.Model):
    vin = models.CharField("Заводской номер машины", max_length=255)

    vehicle_model = models.ForeignKey(VehicleModel, on_delete=models.CASCADE, verbose_name="Модель техники")

    engine_model = models.ForeignKey(EngineModel, on_delete=models.CASCADE, verbose_name="Модель двигателя")

    engine_number = models.CharField("Заводской номер двигателя", max_length=255)

    transmission_model = models.ForeignKey(TransmissionModel, on_delete=models.CASCADE, verbose_name="Модель трансмиссии")
    
    transmission_number = models.CharField("Заводской номер трансмиссии", max_length=255)

    drive_axle = models.ForeignKey(DriveAxleModel, on_delete=models.CASCADE, verbose_name="Модель ведущего моста")
    
    drive_axle_number = models.CharField("Заводской номер ведущего моста", max_length=255)

    steering_axle = models.ForeignKey(SteeringAxleModel, on_delete=models.CASCADE, verbose_name="Модель управляемого моста")

    steering_axle_number = models.CharField("Заводской номер управляемого моста", max_length=255)

    supply_agreement = models.TextField("Договор поставки, №, дата")

    shipment_date = models.DateField("Дата отгрузки с завода")

    consignee = models.TextField("Грузополучатель")

    delivery_address = models.TextField("Адрес поставки (эксплуатации)")

    equipment = models.TextField("Комплектация, доп. опции")

    user = models.ForeignKey(auth_models.CustomUser, on_delete=models.CASCADE, verbose_name="Клиент")

    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name="Сервисная компания")

    def __str__(self):
        return self.vin

    class Meta:
        verbose_name = "Машина"
        verbose_name_plural = "Машины"


"""ТО"""
class Maintenance(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')

    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name='Сервисная компания')

    maintenance_type = models.ForeignKey(MaintenanceType, on_delete=models.CASCADE, verbose_name='Вид ТО')

    maintenance_date = models.DateField(verbose_name='Дата проведения ТО')

    operating_time = models.IntegerField(verbose_name='Наработка мото/часов')

    order = models.CharField(max_length=50, verbose_name='Номер заказа наряда')

    order_date = models.DateField(verbose_name='Дата заказа-наряда')

    def __str__(self):
        return self.car.vin + ' / ' + self.maintenance_type.name

    class Meta:
        verbose_name = 'Техническое обслуживание (ТО)'
        verbose_name_plural = 'Техническое обслуживание (ТО)'
        ordering = ('maintenance_date',)


"""Характер отказа"""
class DenialType(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характер отказа'
        verbose_name_plural = 'Характеры отказов'


"""Рекламация"""
class Complaint(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')

    service_company = models.ForeignKey(ServiceCompany, on_delete=models.SET_NULL, verbose_name='Сервисная компания', null=True)

    date_of_refusal = models.DateField(verbose_name='Дата отказа')

    operating_time = models.IntegerField(verbose_name='Наработка м/час')

    failure_node = models.TextField(verbose_name='Узел отказа')

    denial_type = models.ForeignKey(DenialType, on_delete=models.CASCADE, verbose_name='Характер отказа')

    recovery_method = models.ForeignKey(RecoveryMethod, on_delete=models.CASCADE, verbose_name='Способ восстановления')

    used_details = models.TextField(blank=True, verbose_name='Используемые запасные части')

    date_of_restoration = models.DateField(verbose_name='Дата восстановления')

    equipment_downtime = models.TextField(verbose_name='Время простоя техники')

    def __str__(self):
        return self.car.vin + ' / ' + self.failure_node

    class Meta:
        verbose_name = 'Рекламация'
        verbose_name_plural = 'Рекламации'
        ordering = ['date_of_refusal']

silant-master/silant_proj/main/forms.py
from django import forms
from . import models


class CarSearchForm(forms.Form):
    vin = forms.CharField(max_length=10)


class CarCreateForm(forms.ModelForm):
    class Meta:
        model = models.Car
        fields = '__all__'


class VehicleModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.VehicleModel
        fields = '__all__'


class EngineModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.EngineModel
        fields = '__all__'


class TransmissionModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.TransmissionModel
        fields = '__all__'


class DriveAxleModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.DriveAxleModel
        fields = '__all__'


class SteeringAxleModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.SteeringAxleModel
        fields = '__all__'


class ServiceCompanyCreateForm(forms.ModelForm):
    class Meta:
        model = models.ServiceCompany
        fields = '__all__'


class MaintenanceTypeCreateForm(forms.ModelForm):
    class Meta:
        model = models.MaintenanceType
        fields = '__all__'


class DenialTypeCreateForm(forms.ModelForm):
    class Meta:
        model = models.DenialType
        fields = '__all__'


class RecoveryMethodCreateForm(forms.ModelForm):
    class Meta:
        model = models.RecoveryMethod
        fields = '__all__'


class MaintenanceCreateForm(forms.ModelForm):
    class Meta:
        model = models.Maintenance
        fields = '__all__'
        widgets = {
            'order': forms.Textarea(attrs={'rows': 1}),
            'maintenance_date': forms.NumberInput(attrs={'type': 'date'}),
            'order_date': forms.NumberInput(attrs={'type': 'date'}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }


class ComplaintCreateForm(forms.ModelForm):
    class Meta:
        model = models.Complaint
        fields = '__all__'
        widgets = {
            'date_of_refusal': forms.NumberInput(attrs={'type': 'date'}),
            'failure_node': forms.Textarea(attrs={'rows': 1}),
            'parts_used': forms.Textarea(attrs={'rows': 1}),
            'date_of_restoration': forms.NumberInput(attrs={'type': 'date'}),
            'equipment_downtime': forms.Textarea(attrs={'rows': 1}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }


class MaintenanceUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Maintenance
        fields = '__all__'
        widgets = {
            'order': forms.Textarea(attrs={'rows': 1}),
            'maintenance_date': forms.NumberInput(attrs={'type': 'date'}),
            'order_date': forms.NumberInput(attrs={'type': 'date'}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }

silant-master/silant_proj/templates/main/car/delete.html
{% extends "base.html" %}
{% block content %}
    <h4 class="text-center">Удаление машины:</h4>
    <div class="col-12 col-md-6 offset-md-3 mt-3">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <h3>Вы действительно хотите удалить данную машину?</h3>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a class="btn btn-info" href="/cars/{{ car.pk }}">Назад</a>
            </div>
        </form>
    </div>
{% endblock content %}

silant-master/silant_proj/templates/main/car/edit.html
{% extends "base.html" %}
{% block content %}
    <h4 class="text-center">Редактировать данные:</h4>
    <div class="col-12 col-md-6 offset-md-3 mt-3">
        <form method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="vin">Заводской номер</label>
                <input value="{{ car.vin }}" id="vin" type="text" name="vin" class="form-control" placeholder="Заводской номер">
            </div>
            <div class="form-group">
                <label for="transmission_number">Модель техники</label>
                <select name="vehicle_model" class="form-control">
                    <option disabled>Модель техники</option>
                    {% for vehicle_model in vehicle_models %}
                        {% if vehicle_model.pk == car.vehicle_model.pk %}
                            <option value="{{ vehicle_model.pk }}" selected>{{ vehicle_model.name }}</option>
                        {% else %}
                            <option value="{{ vehicle_model.pk }}">{{ vehicle_model.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="transmission_number">Модель двигателя</label>
                <select name="engine_model" class="form-control">
                    <option disabled>Модель двигателя</option>
                    {% for engine_model in engine_models %}
                        {% if engine_model.pk == car.engine_model.pk %}
                            <option value="{{ engine_model.pk }}" selected>{{ engine_model.name }}</option>
                        {% else %}
                            <option value="{{ engine_model.pk }}">{{ engine_model.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="engine_number">Номер двигателя</label>
                <input value="{{ car.engine_number }}" id="engine_number" type="text" name="engine_number" class="form-control" placeholder="Номер двигателя">
            </div>
            <div class="form-group">
                <label for="transmission_number">Модель трансмиссии</label>
                <select name="transmission_model" class="form-control">
                    <option selected disabled>Модель трансмиссии</option>
                    {% for transmission_model in transmission_models %}
                        {% if transmission_model.pk == car.transmission_model.pk %}
                            <option value="{{ transmission_model.pk }}" selected>{{ transmission_model.name }}</option>
                        {% else %}
                            <option value="{{ transmission_model.pk }}">{{ transmission_model.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="transmission_number">Номер трансмиссии</label>
                <input value="{{ car.transmission_number }}" id="transmission_number" type="text" name="transmission_number" class="form-control" placeholder="Номер трансмиссии">
            </div>
            <div class="form-group">
                <label for="transmission_number">Модель ведущего моста</label>
                <select name="drive_axle" class="form-control">
                    <option selected disabled>Модель ведущего моста</option>
                    {% for drive_axle in drive_axles %}
                        {% if drive_axle.pk == car.drive_axle.pk %}
                            <option value="{{ drive_axle.pk }}" selected>{{ drive_axle.name }}</option>
                        {% else %}
                            <option value="{{ drive_axle.pk }}">{{ drive_axle.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="drive_axle_number">Номер ведущего моста</label>
                <input value="{{ car.drive_axle_number }}" id="drive_axle_number" type="text" name="drive_axle_number" class="form-control" placeholder="Номер ведущего моста">
            </div>
            <div class="form-group">
                <label for="transmission_number">Модель управляемого моста</label>
                <select name="steering_axle" class="form-control">
                    <option selected disabled>Модель управляемого моста</option>
                    {% for steering_axle in steering_axles %}
                        {% if steering_axle.pk == car.steering_axle.pk %}
                            <option value="{{ steering_axle.pk }}" selected>{{ steering_axle.name }}</option>
                        {% else %}
                            <option value="{{ steering_axle.pk }}">{{ steering_axle.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="steering_axle_number">Номер управляемого моста</label>
                <input value="{{ car.steering_axle_number }}" id="steering_axle_number" type="text" name="steering_axle_number" class="form-control" placeholder="Номер управляемого моста">
            </div>
            <div class="form-group">
                <label for="supply_agreement">Договор поставки №, дата.</label>
                <input value="{{ car.supply_agreement }}" id="supply_agreement" type="text" name="supply_agreement" class="form-control" placeholder="Договор поставки №, дата.">
            </div>
            <div class="form-group">
                <input value="{{ car.date }}" type="date" name="shipment_date" class="form-control">
            </div>
            <div class="form-group">
                <label for="consignee">Грузополучатель</label>
                <input value="{{ car.consignee }}" id="consignee" type="text" name="consignee" class="form-control" placeholder="Грузополучатель">
            </div>
            <div class="form-group">
                <label for="delivery_address">Адрес поставки (эксплуатации)"></textare</label>
                <textarea id="delivery_address" rows="2" name="delivery_address" class="form-control" placeholder="Адрес поставки (эксплуатации)">{{ car.delivery_address }}</textarea>
            </div>
            <div class="form-group">
                <label for="equipment">Комплектация (доп. опции)"></textare</label>
                <textarea id="equipment" rows="4" name="equipment" class="form-control" placeholder="Комплектация (доп. опции)">{{ car.equipment }}</textarea>
            </div>
            <div class="form-group">
                <label for="transmission_number">Клиент</label>
                <select name="user" class="form-control">
                    <option selected disabled>Клиент</option>
                    {% for user in users %}
                        {% if user.pk == car.user.pk %}
                            <option value="{{ user.pk }}" selected>{{ user.last_name }} {{ user.first_name }}</option>
                        {% else %}
                            <option value="{{ user.pk }}">{{ user.last_name }} {{ user.first_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="transmission_number">Сервисная организация</label>
                <select name="service_company" class="form-control">
                    <option selected disabled>Сервисная организация</option>
                    {% for service_company in service_companies %}
                        {% if service_company.pk == car.service_company.pk %}
                            <option value="{{ service_company.pk }}" selected>{{ service_company.name }}</option>
                        {% else %}
                            <option value="{{ service_company.pk }}">{{ service_company.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            
            <div class="form-group">
                <button type="submit" class="btn btn-success">Сохранить</button>
                <a class="btn btn-info" href="/cars/{{ car.pk }}">Отмена</a>
            </div>
        </form>
    </div>
{% endblock content %}

silant-master/silant_proj/templates/main/car/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-12 my-4">
            <h5 class="text-center">Подробнее о машине:</h5>
            <div class="card-new p-3">
                <div class="mb-3">
                    <a href="/user_index" class="btn btn-primary">Назад</a>
                    {% if perms.silant.change_car %}
                        <a href="/cars/edit/{{ car.pk }}" class="btn btn-info">Редактировать</a>
                    {% endif %}
                    {% if perms.silant.delete_car %}
                        <a href="/cars/delete/{{ car.pk }}" class="btn btn-danger">Удалить</a>
                    {% endif %}
                </div>
                <table class="table table-hover">
                    <tr><td>Зав. № машины:</td><td>{{ car.vin }}</td></tr>
                    <tr><td>Модель техники:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#vehicle_model">
                        <b>{{ car.vehicle_model.name }}</b></a></td></tr>
                    <tr><td>Модель двигателя:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#engine_model">
                        <b>{{ car.engine_model.name }}</b></a></td></tr>
                    <tr><td>Зав. № двигателя:</td><td>{{ car.engine_number }}</td></tr>
                    <tr><td>Модель трансмиссии:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#transmission_model">
                        <b>{{ car.transmission_model.name }}</b></a></td></tr>
                    <tr><td>Зав. № трансмиссии:</td><td>{{ car.transmission_number }}</td></tr>
                    <tr><td>Модель ведущего моста:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#drive_axle_model">
                        <b>{{ car.drive_axle.name }}</b></a></td></tr>
                    <tr><td>Зав. № ведущего моста:</td><td>{{ car.drive_axle_number }}</td></tr>
                    <tr><td>Модель управляемого моста:</td>
                        <td><a href="#" data-bs-toggle="modal" data-bs-target="#steerable_axle_model">
                            <b>{{ car.steering_axle.name }}</b></a></td></tr>
                    <tr><td>Зав. № управляемого моста:</td><td>{{ car.steering_axle_number }}</td></tr>
                    <tr><td>Договор поставки №, дата:</td><td>{% if car.supply_agreement %}{{ car.supply_agreement }}
                        {% else %}Отсутствует{% endif %}</td></tr>
                    <tr><td>Дата отгрузки с завода:</td><td>{% if car.shipment_date %}
                        {{ car.shipment_date|date:"d.m.Y" }}{% else %}Отсутствует{% endif %}</td></tr>
                    <tr><td>Грузополучатель:</td><td>{% if car.consignee %}{{ car.consignee }}{% else %}Отсутствует{% endif %}</td></tr>
                    <tr><td>Адрес поставки (эксплуатации):</td><td>{% if car.delivery_address %}{{ car.delivery_address }}
                        {% else %}Отсутствует{% endif %}</td></tr>
                    <tr><td>Комплектация (доп. опции):</td><td>{% if car.equipment %}{{ car.equipment }}{% else %}Отсутствует
                        {% endif %}</td></tr>
                    <tr><td>Клиент:</td><td>{% if car.user %}{{ car.user }}{% else %}Отсутствует{% endif %}</td></tr>
                    <tr><td>Сервисная организация:</td><td>{% if car.service_company.name %}<a href="#" data-bs-toggle="modal" data-bs-target="#service_company"><b>{{ car.service_company.name }}</b></a>{% else %}Отсутствует
                        {% endif %}</td></tr>
                </table>
            </div>
        </div>
    <br>

    <div class="modal" tabindex="-1" id="vehicle_model">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-body">
            Описание из справочника:<br><br>
            {% if car.vehicle_model.description %}
                {{ car.vehicle_model.description }}
            {% else %}
                Описание отсутствует
            {% endif %}
            <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Закрыть</button>
        </div>
        </div>
    </div>
    </div>
    <div class="modal" tabindex="-1" id="engine_model">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-body">
            Описание из справочника:<br><br>
            {% if car.engine_model.description %}
                {{ car.engine_model.description }}
            {% else %}
                Описание отсутствует
            {% endif %}
            <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Закрыть</button>
        </div>
        </div>
    </div>
    </div>
    <div class="modal" tabindex="-1" id="transmission_model">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-body">
            Описание из справочника:<br><br>
            {% if car.transmission_model.description %}
                {{ car.transmission_model.description }}
            {% else %}
                Описание отсутствует
            {% endif %}
            <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Закрыть</button>
        </div>
        </div>
    </div>
    </div>
    <div class="modal" tabindex="-1" id="drive_axle_model">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-body">
            Описание из справочника:<br><br>
            {% if car.drive_axle_model.description %}
                {{ car.drive_axle_model.description }}
            {% else %}
                Описание отсутствует
            {% endif %}
            <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Закрыть</button>
        </div>
        </div>
    </div>
    </div>
    <div class="modal" tabindex="-1" id="steerable_axle_model">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-body">
            Описание из справочника:<br><br>
            {% if car.steerable_axle_model.description %}
                {{ car.steerable_axle_model.description }}
            {% else %}
                Описание отсутствует
            {% endif %}
            <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Закрыть</button>
        </div>
        </div>
    </div>
    </div>
    <div class="modal" tabindex="-1" id="service_company">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-body">
            Описание из справочника:<br><br>
            {% if car.service_company.description %}
                {{ car.service_company.description }}
            {% else %}
                Описание отсутствует
            {% endif %}
            <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Закрыть</button>
        </div>
        </div>
    </div>
    </div>
{% endblock content %}