silant-master/silant_proj/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CarListView.as_view(), name="index"),
    path('user_index', views.AdminIndexListView.as_view(), name="user_index"),
    path('cars/new', views.CarCreateView.as_view(), name="car-create"),
    path('cars/<int:pk>', views.CarDetailView.as_view(), name="car-detail"),
    path('cars/edit/<int:pk>', views.CarUpdateView.as_view(), name="car-update"),
    path('cars/delete/<int:pk>', views.CarDeleteView.as_view(), name="car-delete"),

    path('lookups', views.lookups, name="lookups"),

    path('lookups/vehicle_models', views.VehicleModelListView.as_view(), name="vehicle-model-list"),
    path('lookups/vehicle_models/new', views.VehicleModelCreateView.as_view(), name="vehicle-model-create"),
    path('lookups/vehicle_models/edit/<int:pk>', views.VehicleModelUpdateView.as_view(), name="vehicle-model-update"),

    path('lookups/engine_models', views.EngineModelListView.as_view(), name="engine-model-list"),
    path('lookups/engine_models/new', views.EngineModelCreateView.as_view(), name="engine-model-create"),
    path('lookups/engine_models/edit/<int:pk>', views.EngineModelUpdateView.as_view(), name="engine-model-update"),

    path('lookups/transmission_models', views.TransmissionModelListView.as_view(), name="transmission-model-list"),
    path('lookups/transmission_models/new', views.TransmissionModelCreateView.as_view(), name="transmission-model-create"),
    path('lookups/transmission_models/edit/<int:pk>', views.TransmissionModelUpdateView.as_view(), name="transmission-model-update"),

    path('lookups/drive_axles', views.DriveAxleListView.as_view(), name="drive-axle-list"),
    path('lookups/drive_axles/new', views.DriveAxleCreateView.as_view(), name="drive-axle-create"),
    path('lookups/drive_axles/edit/<int:pk>', views.DriveAxleUpdateView.as_view(), name="drive-axle-update"),

    path('lookups/steering_axles', views.SteeringAxleListView.as_view(), name="steering-axle-list"),
    path('lookups/steering_axles/new', views.SteeringAxleCreateView.as_view(), name="steering-axle-create"),
    path('lookups/steering_axles/edit/<int:pk>', views.SteeringAxleUpdateView.as_view(), name="steering-axle-update"),

    path('lookups/service_companies', views.ServiceCompanyListView.as_view(), name="service-company-list"),
    path('lookups/service_companies/new', views.ServiceCompanyCreateView.as_view(), name="service-company-create"),
    path('lookups/service_companies/edit/<int:pk>', views.ServiceCompanyUpdateView.as_view(), name="service-company-update"),

    path('lookups/maintenance_types', views.MaintenanceTypeListView.as_view(), name="maintenance-type-company-list"),
    path('lookups/maintenance_types/new', views.MaintenanceTypeCreateView.as_view(), name="maintenance-type-create"),
    path('lookups/maintenance_types/edit/<int:pk>', views.MaintenanceTypeUpdateView.as_view(), name="maintenance-type-update"),

    path('lookups/denial_types', views.DenialTypeListView.as_view(), name="denial-type-company-list"),
    path('lookups/denial_types/new', views.DenialTypeCreateView.as_view(), name="denial-type-create"),
    path('lookups/denial_types/edit/<int:pk>', views.DenialTypeUpdateView.as_view(), name="denial-type-update"),

    path('lookups/recovery_methods', views.RecoveryMethodListView.as_view(), name="recovery-method-company-list"),
    path('lookups/recovery_methods/new', views.RecoveryMethodCreateView.as_view(), name="recovery-method-create"),
    path('lookups/recovery_methods/edit/<int:pk>', views.RecoveryMethodUpdateView.as_view(), name="recovery-method-update"),

    path('maintenance', views.MaintenanceListView.as_view(), name="maintenance-list"),
    path('maintenance/new', views.MaintenanceCreateView.as_view(), name="maintenance-create"),
    path('maintenance/<int:pk>', views.MaintenanceDetailView.as_view(), name="maintenance-detail"),
    path('maintenance/edit/<int:pk>', views.MaintenanceUpdateView.as_view(), name="maintenance-update"),
    path('maintenance/delete/<int:pk>', views.MaintenanceDeleteView.as_view(), name="maintenance-delete"),

    path('complaints', views.ComplaintListView.as_view(), name="complaint-list"),
    path('complaints/new', views.ComplaintCreateView.as_view(), name="complaint-create"),
    path('complaints/<int:pk>', views.ComplaintDetailView.as_view(), name="complaint-detail"),
    path('complaints/edit/<int:pk>', views.ComplaintUpdateView.as_view(), name="complaint-edit"),
    path('complaints/delete/<int:pk>', views.ComplaintDeleteView.as_view(), name="complaint-delete"),
]

silant-master/silant_proj/silant_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('authentication.urls')),
    path('', include('main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

silant-master/silant_proj/main/models.py
from django.db import models
from authentication import models as auth_models


"""Модель техники"""
class VehicleModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель техники"
        verbose_name_plural = "Модели техники"


"""Модель двигателя"""
class EngineModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель двигателя"
        verbose_name_plural = "Модели двигателя"


"""Модель трансмиссии"""
class TransmissionModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель трансмиссии"
        verbose_name_plural = "Модели трансмиссии"


"""Модель ведущего моста"""
class DriveAxleModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель ведущего моста"
        verbose_name_plural = "Модели ведущего моста"


"""Модель управляемого моста"""
class SteeringAxleModel(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Модель управляемого моста"
        verbose_name_plural = "Модели управляемого моста"


"""Сервисная компания"""
class ServiceCompany(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    user = models.OneToOneField(auth_models.CustomUser, on_delete=models.SET_NULL, verbose_name='Пользователь', null=True)

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Сервисная компания"
        verbose_name_plural = "Сервисные компании"


"""Узел отказа"""
class FailureNode(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Узел отказа"
        verbose_name_plural = "Узлы отказа"


"""Способ восстановления"""
class RecoveryMethod(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Способ восстановления"
        verbose_name_plural = "Способы восстановления"


"""Вид ТО"""
class MaintenanceType(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return super().__str__()

    class Meta:
        verbose_name = "Вид ТО"
        verbose_name_plural = "Виды ТО"


"""Машина"""
class Car(models.Model):
    vin = models.CharField("Заводской номер машины", max_length=255)

    vehicle_model = models.ForeignKey(VehicleModel, on_delete=models.CASCADE, verbose_name="Модель техники")

    engine_model = models.ForeignKey(EngineModel, on_delete=models.CASCADE, verbose_name="Модель двигателя")

    engine_number = models.CharField("Заводской номер двигателя", max_length=255)

    transmission_model = models.ForeignKey(TransmissionModel, on_delete=models.CASCADE, verbose_name="Модель трансмиссии")
    
    transmission_number = models.CharField("Заводской номер трансмиссии", max_length=255)

    drive_axle = models.ForeignKey(DriveAxleModel, on_delete=models.CASCADE, verbose_name="Модель ведущего моста")
    
    drive_axle_number = models.CharField("Заводской номер ведущего моста", max_length=255)

    steering_axle = models.ForeignKey(SteeringAxleModel, on_delete=models.CASCADE, verbose_name="Модель управляемого моста")

    steering_axle_number = models.CharField("Заводской номер управляемого моста", max_length=255)

    supply_agreement = models.TextField("Договор поставки, №, дата")

    shipment_date = models.DateField("Дата отгрузки с завода")

    consignee = models.TextField("Грузополучатель")

    delivery_address = models.TextField("Адрес поставки (эксплуатации)")

    equipment = models.TextField("Комплектация, доп. опции")

    user = models.ForeignKey(auth_models.CustomUser, on_delete=models.CASCADE, verbose_name="Клиент")

    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name="Сервисная компания")

    def __str__(self):
        return self.vin

    class Meta:
        verbose_name = "Машина"
        verbose_name_plural = "Машины"


"""ТО"""
class Maintenance(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')

    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name='Сервисная компания')

    maintenance_type = models.ForeignKey(MaintenanceType, on_delete=models.CASCADE, verbose_name='Вид ТО')

    maintenance_date = models.DateField(verbose_name='Дата проведения ТО')

    operating_time = models.IntegerField(verbose_name='Наработка мото/часов')

    order = models.CharField(max_length=50, verbose_name='Номер заказа наряда')

    order_date = models.DateField(verbose_name='Дата заказа-наряда')

    def __str__(self):
        return self.car.vin + ' / ' + self.maintenance_type.name

    class Meta:
        verbose_name = 'Техническое обслуживание (ТО)'
        verbose_name_plural = 'Техническое обслуживание (ТО)'
        ordering = ('maintenance_date',)


"""Характер отказа"""
class DenialType(models.Model):
    name = models.CharField("Название", max_length=255)

    description = models.TextField("Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характер отказа'
        verbose_name_plural = 'Характеры отказов'


"""Рекламация"""
class Complaint(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')

    service_company = models.ForeignKey(ServiceCompany, on_delete=models.SET_NULL, verbose_name='Сервисная компания', null=True)

    date_of_refusal = models.DateField(verbose_name='Дата отказа')

    operating_time = models.IntegerField(verbose_name='Наработка м/час')

    failure_node = models.TextField(verbose_name='Узел отказа')

    denial_type = models.ForeignKey(DenialType, on_delete=models.CASCADE, verbose_name='Характер отказа')

    recovery_method = models.ForeignKey(RecoveryMethod, on_delete=models.CASCADE, verbose_name='Способ восстановления')

    used_details = models.TextField(blank=True, verbose_name='Используемые запасные части')

    date_of_restoration = models.DateField(verbose_name='Дата восстановления')

    equipment_downtime = models.TextField(verbose_name='Время простоя техники')

    def __str__(self):
        return self.car.vin + ' / ' + self.failure_node

    class Meta:
        verbose_name = 'Рекламация'
        verbose_name_plural = 'Рекламации'
        ordering = ['date_of_refusal']

silant-master/silant_proj/main/forms.py
from django import forms
from . import models


class CarSearchForm(forms.Form):
    vin = forms.CharField(max_length=10)


class CarCreateForm(forms.ModelForm):
    class Meta:
        model = models.Car
        fields = '__all__'


class VehicleModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.VehicleModel
        fields = '__all__'


class EngineModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.EngineModel
        fields = '__all__'


class TransmissionModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.TransmissionModel
        fields = '__all__'


class DriveAxleModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.DriveAxleModel
        fields = '__all__'


class SteeringAxleModelCreateForm(forms.ModelForm):
    class Meta:
        model = models.SteeringAxleModel
        fields = '__all__'


class ServiceCompanyCreateForm(forms.ModelForm):
    class Meta:
        model = models.ServiceCompany
        fields = '__all__'


class MaintenanceTypeCreateForm(forms.ModelForm):
    class Meta:
        model = models.MaintenanceType
        fields = '__all__'


class DenialTypeCreateForm(forms.ModelForm):
    class Meta:
        model = models.DenialType
        fields = '__all__'


class RecoveryMethodCreateForm(forms.ModelForm):
    class Meta:
        model = models.RecoveryMethod
        fields = '__all__'


class MaintenanceCreateForm(forms.ModelForm):
    class Meta:
        model = models.Maintenance
        fields = '__all__'
        widgets = {
            'order': forms.Textarea(attrs={'rows': 1}),
            'maintenance_date': forms.NumberInput(attrs={'type': 'date'}),
            'order_date': forms.NumberInput(attrs={'type': 'date'}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }


class ComplaintCreateForm(forms.ModelForm):
    class Meta:
        model = models.Complaint
        fields = '__all__'
        widgets = {
            'date_of_refusal': forms.NumberInput(attrs={'type': 'date'}),
            'failure_node': forms.Textarea(attrs={'rows': 1}),
            'parts_used': forms.Textarea(attrs={'rows': 1}),
            'date_of_restoration': forms.NumberInput(attrs={'type': 'date'}),
            'equipment_downtime': forms.Textarea(attrs={'rows': 1}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }


class MaintenanceUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Maintenance
        fields = '__all__'
        widgets = {
            'order': forms.Textarea(attrs={'rows': 1}),
            'maintenance_date': forms.NumberInput(attrs={'type': 'date'}),
            'order_date': forms.NumberInput(attrs={'type': 'date'}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }

silant-master/silant_proj/templates/main/complaints/delete.html
{% extends "base.html" %}
{% block content %}
    <h4 class="text-center">Удаление рекламации</h4>
    <div class="col-12 col-md-6 offset-md-3 mt-3">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <h3>Вы действительно хотите удалить данную рекламацию?</h3>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a class="btn btn-info" href="/complaints/{{ object.pk }}">Назад</a>
            </div>
        </form>
    </div>
{% endblock content %}

silant-master/silant_proj/templates/main/complaints/edit.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block content %}
    <h4 class="text-center">Редактирование рекламации</h4>
    <div class="col-12 col-md-6 offset-md-3 mt-3">
        <form method="post">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    <strong>Пожалуйста, исправьте ошибки:</strong>
                    <ul>
                        {% if form.non_field_errors %}
                            <li>{{ form.non_field_errors }}</li>
                        {% endif %}
                        {% for field in form %}
                            {% if field.errors %}
                            <li>
                                {{ field.label }}
                                <ul class="errorlist">
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                                </ul>
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="form-group">
                <label for="date_of_refusal">Дата отказа</label>
                <input type="date" id="date_of_refusal" name="date_of_refusal" value="{{ form.instance.date_of_refusal|date:'Y-m-d' }}" class="form-control">
            </div>
            <div class="form-group">
                {{ form.service_company }}
                <input type="hidden" name="car" value="{{ form.instance.car.pk }}">
            </div>
            <div class="form-group">
                <input type="number" name="operating_time" class="form-control" value="{{ form.instance.operating_time }}" placeholder="Наработка м/час">
            </div>
            <div class="form-group">
                <input type="text" name="failure_node" class="form-control" value="{{ form.instance.failure_node }}" placeholder="Узел отказа">
            </div>
            <div class="form-group">
                <select name="denial_type" class="form-control">
                    <option selected disabled>Характер отказа</option>
                    {% for denial_type in denial_types %}
                        {% if denial_type.pk == form.instance.denial_type.pk %}    
                            <option value="{{ denial_type.pk }}" selected>{{ denial_type.name }}</option>
                        {% else %}
                            <option value="{{ denial_type.pk }}">{{ denial_type.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <select name="recovery_method" class="form-control">
                    <option selected disabled>Способ восстановления</option>
                    {% for recovery_method in recovery_methods %}
                        {% if recovery_method.pk == form.instance.recovery_method.pk %}    
                            <option value="{{ recovery_method.pk }}" selected>{{ recovery_method.name }}</option>
                        {% else %}
                            <option value="{{ recovery_method.pk }}">{{ recovery_method.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <input type="text" name="used_details" value="{{ form.instance.used_details }}" class="form-control" placeholder="Используемые запасные части">
            </div>
            <div class="form-group">
                <label for="date_of_restoration">Дата восстановления</label>
                <input type="date" id="date_of_restoration" value="{{ form.instance.date_of_restoration|date:'Y-m-d' }}" name="date_of_restoration" class="form-control">
            </div>
            <div class="form-group">
                <input type="text" name="equipment_downtime" value="{{ form.instance.equipment_downtime }}" class="form-control" placeholder="Время простоя техники">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Сохранить</button>
                <a href="/complaints/{{ form.instance.pk }}" class="btn btn-info">Назад</a>
            </div>
        </form>
    </div>
{% endblock content %}

silant-master/silant_proj/templates/main/complaints/index.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block content %}
<div class="row">
    <div class="col-12 my-4">
        <div class="card-new p-3">
            <div class="mb-2">
                <a href="/complaints" class="btn btn-info">Назад</a>
                {% if perms.silant.change_maintenance %}
                    <a href="/complaints/edit/{{ complaint.pk }}" class="btn btn-info">Редактировать</a>
                {% endif %}
                {% if perms.silant.delete_maintenance %}
                    <a href="/complaints/delete/{{ complaint.pk }}" class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>

            <h4 class="">Данные о рекламации</h4>
            <div class="text-center">
                <table class="table table-hover">
                    <tr><td>Зав. №  машины:</td><td>{{ complaint.car }}</td></tr>
                    <tr><td>Сервисная организация:</td><td><a href="#" data-toggle="modal" data-target="#service_company"><b>{{ complaint.service_company.name }}</b></a></td></tr>
                    <tr><td>Дата отказа:</td><td>{{ complaint.date_of_refusal }}</td></tr>
                    <tr><td>Наработка м/час:</td><td>{{ complaint.operating_time }}</td></tr>
                    <tr><td>Узел отказа:</td><td>{{ complaint.failure_node }}</td></tr>
                    <tr><td>Характер отказа:</td><td><a href="#" data-toggle="modal" data-target="#description_failure"><b>{{ complaint.denial_type.name }}</b></a></td></tr>
                    <tr><td>Способ восстановления:</td><td><a href="#" data-toggle="modal" data-target="#recovery_method"><b>{{ complaint.recovery_method }}</b></a></td></tr>
                    <tr><td>Используемые запасные части:</td><td>{{ complaint.used_details }}</td></tr>
                    <tr><td>Дата восстановления:</td><td>{{ complaint.date_of_restoration }}</td></tr>
                    <tr><td>Время простоя техники:</td><td>{{ complaint.equipment_downtime }}</td></tr>
                </table>
            </div>

            <div class="modal fade" tabindex="-1" id="service_company">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            Описание из справочника:<br><br>
                            {% if complaint.service_company.description %}
                                {{ complaint.service_company.description }}
                            {% else %}
                                Описание отсутствует
                            {% endif %}
                            <br><br><button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" tabindex="-1" id="description_failure">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            Описание из справочника:<br><br>
                            {% if complaint.denial_type.description %}
                                {{ complaint.denial_type.description }}
                            {% else %}
                                Описание отсутствует
                            {% endif %}
                            <br><br><button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" tabindex="-1" id="description_failure">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            Описание из справочника:<br><br>
                            {% if complaint.description_failure.description %}
                                {{ complaint.description_failure.description }}
                            {% else %}
                                Описание отсутствует
                            {% endif %}
                            <br><br><button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" tabindex="-1" id="recovery_method">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            Описание из справочника:<br><br>
                            {% if complaint.recovery_method.description %}
                                {{ complaint.recovery_method.description }}
                            {% else %}
                                Описание отсутствует
                            {% endif %}
                            <br><br><button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

silant-master/silant_proj/templates/main/complaints/list.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block content %}
    <h4 class="text-center mt-4"></h4>
    <div class="col-12 col-md-12 mt-3">
        <div class="card-new p-4">
            <div class="d-flex justify-content-around">
                <a href="/user_index" class="pt-0 h3 text-uppercase nav-link {% if request.path|slice:":11" == '/user_index' %}font-weight-bold text-info{% else %}text-dark{% endif %}">машины</a>
                <a href="/maintenance" class="pt-0 h3 text-uppercase nav-link {% if request.path|slice:":12" == '/maintenance' %}font-weight-bold text-info{% else %}text-dark{% endif %}">то</a>
                <a href="/complaints" class="pt-0 h3 text-uppercase nav-link {% if request.path|slice:":12" == '/complaints' %}font-weight-bold text-info{% else %}text-dark{% endif %}">рекламации</a>
            </div>
            <h4 class="text-center my-3">Информация о рекламациях вашей техники:</h4>
            <div class="d-flex justify-content-between align-items-end my-3">
                <div>
                    <span class="select_name">сервисная компания</span>
                    <select class="form-control" onchange="window.location.assign('?sc=' + this.value);">
                        <option value="{{ sc }}">&nbsp;{{ sc }}&nbsp;</option>
                        {% for item in service_company %}
                            {% if item %}
                                <option value="{{ item }}">&nbsp;{{ item }}&nbsp;</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <span class="select_name">узел отказа</span>
                    <select class="form-control" onchange="window.location.assign('?fn=' + this.value);">
                        <option value="{{ fn }}">&nbsp;{{ fn }}&nbsp;</option>
                        {% for item in failure_node %}
                            <option value="{{ item }}">&nbsp;{{ item }}&nbsp;</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <span class="select_name">способ восстановления</span>
                    <select class="form-control" onchange="window.location.assign('?rm=' + this.value);">
                        <option value="{{ rm }}">&nbsp;{{ rm }}&nbsp;</option>
                        {% for item in recovery_method %}
                            <option value="{{ item }}">&nbsp;{{ item }}&nbsp;</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <a title="Очистить фильтры" class="btn btn-primary" href="?clear=clear">Сбросить</a>
                </div>
            </div>
            <table class="table table-hover">
                <tr>
                    <th><a title="Сортировать" href="?order_by=car">&#9650; </a>Машина<br>
                        <a title="Сортировать" href="?order_by=service_company">&#9650; </a>Сервисная организация</th>
                    <th><a title="Сортировать" href="?order_by=date_of_refusal">&#9650; </a>Дата отказа<br>
                        <a title="Сортировать" href="?order_by=operating_time">&#9650; </a>Наработка</th>
                    <th><a title="Сортировать" href="?order_by=failure_node">&#9650; </a>Узел отказа<br>
                        <a title="Сортировать" href="?order_by=denial_type">&#9650; </a>Характер отказа</th>
                    <th><a title="Сортировать" href="?order_by=recovery_method">&#9650; </a>Способ восстановления<br>
                        <a title="Сортировать" href="?order_by=used_details">&#9650; </a>Используемые запасные части</th>
                    <th><a title="Сортировать" href="?order_by=date_of_restoration">&#9650; </a>Дата восстановления<br>
                        <a title="Сортировать" href="?order_by=equipment_downtime">&#9650; </a>Время простоя техники</th>
                    <th>Действия</th>
                </tr>
                {% for complaint in complaints %}
                    <tr>
                        <td>{{ complaint.car.vin }}<br>
                            {{ complaint.service_company.name }}</td>
                        <td>{{ complaint.date_of_refusal|date:"d.m.Y" }}<br>
                            {{ complaint.operating_time }}</td>
                        <td>{{ complaint.failure_node }}<br>
                            {{ complaint.denial_type }}</td>
                        <td>{{ complaint.recovery_method }}<br>
                            {{ complaint.used_details }}</td>
                        <td>{{ complaint.date_of_restoration|date:"d.m.Y" }}<br>
                            {{ complaint.equipment_downtime }}</td>
                        <td><a href="/complaints/{{ complaint.pk }}" class="btn btn-info">Подробнее</a></td>
                    </tr>
                {% endfor %}
            </table>
            <div class="text-center">
                {% if request.user|has_group:"service" or request.user|has_group:"manager" or request.user|has_group:"admin" %}
                    <a class="btn btn-primary" href="/complaints/new">Добавить новую запись о рекламации</a>
                {% endif %}
                {% if request.user|has_group:"manager" or request.user|has_group:"admin" %}
                    <a class="btn btn-primary" href="/lookups" role="button">Редактор справочников</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}